# Generated by Django 4.0.3 on 2022-03-14 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeseries_name', models.CharField(max_length=1000)),
                ('province_state', models.CharField(max_length=1000)),
                ('country_region', models.CharField(max_length=1000)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('cases', models.IntegerField()),
                ('timeseries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_series.timeseries')),
            ],
        ),
    ]
