# Generated by Django 4.0.3 on 2022-03-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseries',
            name='type',
            field=models.CharField(choices=[('D', 'Deaths'), ('C', 'Confirmed'), ('R', 'Recovered')], max_length=1),
        ),
        migrations.AlterField(
            model_name='timeseriesdata',
            name='date',
            field=models.CharField(max_length=1000),
        ),
    ]
