# Generated by Django 4.0.3 on 2022-03-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_series', '0002_alter_timeseries_type_alter_timeseriesdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseries',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='timeseriesdata',
            name='cases',
            field=models.IntegerField(default=-1),
        ),
    ]
