# Generated by Django 4.0.3 on 2022-03-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_series', '0003_alter_timeseries_latitude_alter_timeseries_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseries',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='timeseriesdata',
            name='cases',
            field=models.IntegerField(),
        ),
    ]
