# Generated by Django 4.0.3 on 2022-03-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreports',
            old_name='incident_rate',
            new_name='incidence_rate',
        ),
    ]
