# Generated by Django 4.0.3 on 2022-03-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailyreport_name', models.CharField(max_length=1000)),
                ('fips', models.IntegerField()),
                ('admin2', models.CharField(max_length=1000)),
                ('province_state', models.CharField(max_length=1000)),
                ('country_region', models.CharField(max_length=1000)),
                ('last_update', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('confirmed', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('active', models.IntegerField()),
                ('combined_key', models.CharField(max_length=1000)),
                ('incident_rate', models.FloatField()),
                ('case_fatality_ratio', models.FloatField()),
            ],
        ),
    ]
