# Generated by Django 4.0.3 on 2022-03-20 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_series', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeseriesdata',
            name='xd',
        ),
    ]
